config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create, :index, :show] do
    resource :receipt
  end

  resources :dashboard, only: [:index]

  root to: 'dashboard#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  belongs_to :customer, optional: true
  accepts_nested_attributes_for :line_items
  enum sales_channel: { Online: 0, CX: 1, Retail: 2 }

  after_validation :set_amount

  private
  def set_amount
    self.amount = line_items.map(&:product).map(&:cost).inject(:+)
  end

  def self.sales_channel_keys
    sales_channels.keys
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @orders = Order.all.decorate
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @order.line_items.build
  end

  def create
    @order = Order.new(order_params)
    if @order.valid?
      @order.save
      redirect_to order_receipt_path(@order)
    else
      render :new
    end
  end

  private
  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :name, :product_id ])
  end

  def products
    @products ||= Product.all
  end
  helper_method :products
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def show
    @order = Order.find_by(id: params[:order_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def price_of(product)
    number_to_currency(product.cost)
  end
end

app/views/application/_error_messages.html.erb
<%- if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this order from being saved:
    </h2>
    <ul>
      <%- object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

app/views/dashboard/index.html.erb
<p><%= link_to 'Orders', '#', id: 'order_list' %></p>

<div class="root">
<div id="orders">
  <div class="sales-channel-filter">
    <span>Filter by <button class="dropbtn">Sales Channel</button></span>
    <div class="dropdown-content">
      <% Order.sales_channel_keys.each do |sales_channel| %>
        <%= link_to sales_channel, '#', class: sales_channel.parameterize %>
      <% end %>
    </div>
  </div>
  <table id="order-table">
    <tr class="header">
      <th>Order Number</th>
      <th>Customer</th>
      <th>Date Created</th>
    </tr>
    <% @orders.each do |order| %>
      <tr class="<%= order.sales_channel.parameterize %>">
      <td><%= order.id %></td>
      <td><%= order.customer.name %></td>
      <td><%= order.created_at %></td>
      </tr>
    <% end %>
  </table>
</div>
</div>

app/views/dashboard/show.html.erb
<h1>Tuft &amp; Needle</h1>

<h2 align=center>&amp;Introduction</h2>

<p>Thank you for your interest in joining the team at Tuft & Needle! This Rails application is a very small sampling of the kind of application that you would be working on as a developer at T&N. We've designed a few features for you to work through that will help us get a feel for where you are in your journey as a developer and will hopefully give you some small insight into what it's like to work with us. This application has basic pages setup to <%= link_to 'create an Order', new_order_path %> of mattresses and view the details of that Order. Below are some enhancements to the application to work through. You may choose any or all of these features to work on. Feel free to add or subtract anything you want from this application from gems, to the database schema, to business logic and tests. A cucumber suite as well as a mini test suite has been started and may be extended if you choose.</p>

<br />

<h2 align=center>&amp;Stories</h2>

<h3>(1) Customer views items in cart grouped by product</h3>

<pre>
In order to provide a clear shopping experience
As a customer adding multiple items to my shopping cart
I want to see the products I've added, that are the same, grouped together

Given the following products
- King Mattress
- Queen Mattress
- Twin Mattress

When I select "King Mattress $700.00"
And I click "Add to Cart"
Then I should see "King Mattress $700.00" in my shopping cart

When I select "King Mattress $700.00"
And I click "Add to Cart"
Then I should see "(2) King Mattress $1400.00" in my shopping cart
</pre>

<h3>(2) Customer experience representative views order list</h3>

<pre>
In order to view all of the recent orders
As a customer experience representative on my dashboard
I want to see a list of all the recent orders

Given 5 recent orders
When I am on the dashboard page
And I click "Orders"
Then I should see a list in the following format:
  | Order Number | Customer | Date Created |
  | 1            | Jane Doe | 01/01/2017   |
</pre>

<h3>(3) Customer experience representative views sales channel for an order</h3>

<pre>
In order to see where an order originated from
As a customer experience representative viewing the details of an order
I want to see the sales channel for that order

- For an order placed by a customer the sales channel should be 'Online'
- For an order placed by a customer experience representative the sales channel should be 'CX'
- For an order placed in a retail store the sales channel should be 'Retail'

Given an order placed Online
When I am on the detail page for that order
Then I should see the sales channel 'Online' reflected

Given an order placed by a customer service representative
When I am on the detail page for that order
Then I should see the sales channel 'CX' reflected

Given an order placed in a retail location
When I am on the detail page for that order
Then I should see the sales channel 'Retail' reflected
</pre>

<h3>(4) Customer experience representative views orders list sorted by sales channel</h3>

<pre>
In order to see orders by different sales channels
As a customer experience representative viewing the orders list
I want to filter the order list by sales channel

Given an order placed Online
And an order placed by CX
And I am viewing the orders lists
When I filter the list by 'Online' orders
Then I should see Online orders
And I should not see CX orders
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= render partial: "error_messages", locals: { object: @order } %>

<p>
  <%= f.fields_for :line_items do |ff| %>
    <%- products.each do |product| %>
      <%= ff.label :product_id, product.name, for: "order_line_items_attributes_0_product_id_#{product.id}" do %>
        <span><%= product.name %> <%= price_of(product) %></span>
      <% end %>
      <%= ff.radio_button :product_id, product.id, data: { price: price_of(product), dimensions: product.dimensions } %>
    <% end %>
  <% end %>
</p>

<div id="product_details"></div>

<p><%= link_to 'Add To Cart', '#', id: 'add_to_cart' %></p>

<div id="cart"></div>

<p><%= f.submit 'Checkout' %>

app/views/orders/index.html.erb
<h1>Orders</h1>

app/views/orders/new.html.erb
<%= form_for @order do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/orders/show.html.erb
<%= render "shared/order_info" %>

<div id="sales-channel">
  <p><b>Sales Channel:</b> <%= @order.sales_channel %></p>
</div>

app/views/receipts/show.html.erb
<p> Thank you for completing your purchase.</p>

<%= render "shared/order_info" %>

app/views/shared/_order_info.html.erb
<p>Order Summary</p>
<p>Items</p>
<ul>
  <%- @order.line_items.each do |li| %>
    <li><%= li.product.name %> - <%= number_to_currency(li.product.cost) %></li>
  <% end %>
</ul>

<p>Total: <%= number_to_currency(@order.amount) %></p>